services:
  - type: web
    name: rairu-kun
    env: docker
    plan: free
    buildCommand: npm install && node deploy-commands.js
    startCommand: node index.js
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
